### ISSUE TITLE
Carbon is now updated to 0.2.0

### ISSUE THREAD

**Issue by jwoertink** [keizo3/carbon_aws_ses_adapter#7]
https://github.com/keizo3/carbon_aws_ses_adapter/blob/5d85128d42283419eea210281b6218ec1f8bd217/shard.yml#L16

This shard should still be compatible. We bumped to 0.2.0 because the SendGrid adapter is no longer built-in. You might be able to just set the requirement to `>= 0.1.4`

**Comment by keizo3** [comment]
@jwoertink 
Thank you for your suggestion!
fix carbon_aws_ses_adapter/shard.yml and close issue
